apiVersion: v1
kind: Service
metadata:
  name: rserve-service
spec:
  selector:
    app: rserve
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rserve-deployment
spec:
  selector:
    matchLabels:
      app: rserve
  replicas: 2
  template:
    metadata:
      labels:
        app: rserve
    spec:
      containers:
        - name: rserve
          image: kapps/jobqueue:queue_rserve
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "1"
          ports:
            - containerPort: 8000