apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-deployment
spec:
  selector:
    matchLabels:
      app: celery
  replicas: 2
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - name: celery
          image: kapps/jobqueue:queue_celery
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
          args: ["worker", "-l", "info", "-A", "tasks", "-O", "fair"]
