apiVersion: v1
kind: Service
metadata:
  name: celery-service
spec:
  selector:
    app: celery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-deployment
spec:
  selector:
    matchLabels:
      app: celery
  replicas: 2
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - name: celery
          image: kapps/jobqueue:queue_celery
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
          ports:
            - containerPort: 80