apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  selector:
    app: main
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
spec:
  selector:
    matchLabels:
      app: main
  replicas: 2
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
        - name: main
          image: kapps/jobqueue:webservice
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: RSERVE_HOST
              value: rserve-service
            - name: RSERVE_PORT
              value: "8000"
          ports:
            - containerPort: 9000
