version: "3.7"
services:
  redis:
    image: bitnami/redis:5.0
    container_name: redis
    networks:
      - app-tier
    expose:
      - '6379'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  # webservice:
  #   build:
  #     context: .
  #   image: webservice
  #   container_name: webservice
  #   networks:
  #     - app-tier
  #   depends_on:
  #     - redis
  #     - job_queue
  #   environment:
  #     CELERY_BACKEND_HOST: redis
  #     CELERY_BACKEND_PORT: '6379'
  #     CELERY_BROKER_HOST: redis
  #     CELERY_BROKER_PORT: '6379'

networks:
  app-tier:
    name: app-tier-network
    driver: bridge
