version: "3.7"
services:
  redis:
    image: bitnami/redis:5.0
    container_name: redis
    networks:
      - app-tier
    expose:
      - '6379'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  queue_rserve:
    image: queue_rserve
    container_name: queue_rserve
    networks:
      - app-tier
    ports:
      - 8000:8000
      - 6311:6311
    depends_on:
      - redis
    volumes:
      - ./:/home/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_DB: "1"
    command: [
      "--slave", "--RS-conf", "/home/app/rserve.conf", "--RS-source", "/home/app/rserve-src.R"
    ]

networks:
  app-tier:
    name: app-tier-network
    driver: bridge
